### PR TITLE
Factor out the common part of the PBKDF2 algorithm

### PR DESCRIPTION
**Pull request by wiml**
The three PBKDF2 functions were just duplicates of each other with one line changed. This PR combines them into one function with an extra argument.

### CODE REVIEW

**Comment by Ruffio** [comment]
@alippai how does this PR look? Ready to merged?

**Comment by alippai** [comment]
This didn't pass the TypeScript type checking, so reverted it back.

**Comment by wiml** [comment]
@alippai  What was the error? I'm pretty sure I typechecked it before opening the PR.

The committed version seems a little bit brittle, since it has to list every PRF, instead of simply allowing any object of the correct type.

**Comment by alippai** [comment]
@wiml here is the failing commit, after turning on the error reporting: https://travis-ci.org/asmcrypto/asmcrypto.js/jobs/450175452

The new solution can be tuned, indeed. The overall quality of OOP is bad in this project, because it's based on legacy code.

**Comment by wiml** [comment]
Ah, I see! Well if minor tuning / cleanup PRs are accepted, I might make some when I have some spare time.

**Pull request merged**
