### PR TITLE
Refactored to use ES6 modules and bundle with rollup

### PR DESCRIPTION
**Pull request by porcellus**
As proposed in issue #119 
I tried to disturb the least amount of code and kept the general structure, but some restructuring was needed to keep the interface and to avoid assigning to imported values.
Locally all tests passed.

### CODE REVIEW

**Comment by porcellus** [comment]
Also, I had to increase the test timeout because the some tests timed out on my PC

**Comment by dignifiedquire** [comment]
@vibornoff any feedback on this? do you have intentions of merging this?

**Comment by vibornoff** [comment]
@dignifiedquire , sorry, I'm out of spare time.

**Comment by dignifiedquire** [comment]
@vibornoff Thanks for the quick reply. No need to be sorry. I am going to do some experiments with this branch and see if I can get things into a good state on my fork for now.

**Comment by alippai** [comment]
Bump

**Comment by alippai** [comment]
@vibornoff can we help? What do you need to be able to merge this?

**Comment by vibornoff** [comment]
@alippai , open gitter.im please

**Pull request merged**
